# Generated by Django 5.1.4 on 2025-03-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
    ]
