/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Blog: typeof import('./components/Blog.vue')['default']
    CreateBlog: typeof import('./components/CreateBlog.vue')['default']
    CreateRecipe: typeof import('./components/CreateRecipe.vue')['default']
    FirstForm: typeof import('./components/Forms/FirstForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    IngredientsForm: typeof import('./components/Forms/IngredientsForm.vue')['default']
    Recipe: typeof import('./components/Recipe.vue')['default']
    RecipeModal: typeof import('./components/RecipeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
